spring:
  data:
     elasticsearch:
        #elasticsearch\u670D\u52A1\u5730\u5740\uFF0C\u9ED8\u8BA4\u7AEF\u53E3\u4E3A9300
        cluster-nodes: 192.168.237.130:9300
        #\u8282\u70B9\u540D\u5B57\uFF0C\u9ED8\u8BA4elasticsearch
        cluster-name: docker-cluster